---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks.
  include: "{{ ansible_os_family }}.yml"

- name: Create stub apache.conf file
  copy:
    dest: "{{ aegir_user_home }}/config/apache.conf"
    content: ''
    owner: "{{ aegir_user_name }}"
    group: "{{ aegir_user_name }}"
    force: no

- name: Add Aegir user to sudoers to reload Apache
  lineinfile:
    dest: '{{ aegir_apache_sudoers_file }}'
    regexp: '^{{ aegir_user_name }}'
    line: '{{ aegir_user_name }} ALL=NOPASSWD: {{ aegir_apache_control }}'
    state: present
    validate: 'visudo -cf %s'
    create: yes

- name: Add Aegir to Apache group.
  user:
    name: "{{ aegir_user_name }}"
    groups: "{{ aegir_apache_group }}"
    append: yes
  when: aegir_apache_user_in_apache_group

- name: "Post Install on {{ ansible_os_family }}"
  include: "post-install-{{ ansible_os_family }}.yml"
